# Generated by Django 6.0.2 on 2026-03-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('Class', models.CharField(max_length=20)),
                ('Gender', models.CharField(max_length=10)),
                ('pname', models.CharField(max_length=50)),
                ('pcontact', models.CharField(max_length=15)),
                ('pemail', models.EmailField(max_length=254)),
            ],
        ),
    ]
