# Generated by Django 6.0.2 on 2026-04-12 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_staff', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='student_class',
            new_name='Class',
        ),
    ]
