# Generated by Django 6.0.2 on 2026-04-13 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_staff', '0002_rename_student_class_person_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_staff.class'),
        ),
    ]
