# Generated by Django 6.0.2 on 2026-04-13 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_staff', '0003_alter_person_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='grade',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='total',
            field=models.IntegerField(blank=True, max_length=3, null=True),
        ),
    ]
