# Generated by Django 6.0.2 on 2026-04-13 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_staff', '0004_report_grade_report_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='term',
            field=models.CharField(blank=True, choices=[('Term 1', 'Term 1'), ('Term 2', 'Term 2'), ('Term 3', 'Term 3')], max_length=10, null=True),
        ),
    ]
