# Generated by Django 6.0.2 on 2026-04-13 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_staff', '0005_report_term'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='term',
            new_name='terms',
        ),
    ]
