# Generated by Django 6.0.2 on 2026-04-15 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_staff', '0006_rename_term_report_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='app_staff.person'),
        ),
        migrations.AlterField(
            model_name='report',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
