# Generated by Django 6.0.2 on 2026-04-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_staff', '0007_alter_report_student_alter_report_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
